# Fake logging configuration
default:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
    - file

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/app.log
    maxBytes: 10485760
    backupCount: 5
